### ISSUE TITLE
Trigger hotkey by name only works halfway

### ISSUE THREAD

**Issue by electricplant** [aatikturk/obsws-python#13]
Hello! 

I am trying to run a bit of code to show and then hide a scene item. (example, show video, then hide)
The problem is that it will only work partly. For example if I send:
`cl.trigger_hot_key_by_name('libobs.show_scene_item.FLASHBANG')` (my scene name is FLASHBANG, a short video)
it will successfully play, but then when I send:
`cl.trigger_hot_key_by_name('libobs.hide_scene_item.FLASHBANG')`  
nothing happens. 

The weirdest part, sometimes this only works the other way around. 
I stripped all my code until I got the simplest bit with the error:

`import obsws_python as obs
from time import sleep

cl = obs.ReqClient()

cl.trigger_hot_key_by_name('libobs.show_scene_item.FLASHBANG')
sleep(2)
cl.trigger_hot_key_by_name('libobs.hide_scene_item.FLASHBANG')`

I'll also include my config.toml if that helps (removing my password of course)
`[connection]
host = "192.168.0.21"
port = ####
password = "####"
`

Last thing to mention; I've tried this with multiple scenes (text, image), same issue all around.

**Comment by onyx-and-iris** [comment]
Hi! Thanks for raising the issue.

I've noticed similar behaviour when trying to mute/unmute sources as well as duplicates in the hotkeylist. Perhaps it is related to [this issue](https://github.com/obsproject/obs-websocket/issues/1001)

I don't think there is anything wrong with your code and I'm not sure it can be fixed at the level of this wrapper. I suspect it may be a bug with the TriggerHotkeyByName feature.

**Comment by electricplant** [comment]
> 

Darn! I was hoping my code was the issue. Ah well at least I found a workaround. Just using the "trigger_hot_key_by_key_sequence" works.
