### ISSUE TITLE
pwinstaller misses obsws

### ISSUE THREAD

**Issue by hmriit** [aatikturk/obsws-python#15]
I have a simple script, and step 1 is :   import obsws_python as obs

It works great when run as `python script.py`

But then when I do a pyinstaller --onefile script.py  

It keeps missing obsws.  When I run the resulting EXE i get:

```
Traceback (most recent call last):
  File "myscript.py", line 7, in <module>
    import obsws_python as obs
ModuleNotFoundError: No module named 'obsws_python'
[4408] Failed to execute script 'myscript' due to unhandled exception!
```

Is there something you can include in the package so that obsws can be included in a pwinstaller?   I have tried the usual --include-hidden type options already.

Note: all my other import modules are working fine.

ta

**Comment by onyx-and-iris** [comment]
Hi! 

Did you install obsws_python into the environment you're using to build the exe? I just tried building the events example and it built and ran fine. I used exactly `pyinstaller --onefile script.py`

**Comment by onyx-and-iris** [comment]
Closing as nonresponsive. Wasn't able to reproduce myself.
