### ISSUE TITLE
Error in set_scene_item_index request

### ISSUE THREAD

**Issue by pedrojfernandez** [aatikturk/obsws-python#22]
def set_scene_item_index(self, scene_name, item_id, item_index):
        """
        Sets the index position of a scene item in a scene.
        Scenes and Groups
        :param scene_name: Name of the scene the item is in
        :type scene_name: str
        :param item_id: Numeric ID of the scene item (>= 0)
        :type item_id: int
        :param item_index: New index position of the scene item (>= 0)
        :type item_index: int
        """
        payload = {
            "sceneName": scene_name,
            "sceneItemId": item_id,
            "sceneItemLocked": item_index,   **<---  this should be sceneItemIndex**
        }
        self.send("SetSceneItemIndex", payload)

**Comment by aatikturk** [comment]
That's a good catch.  Thanks for pointing out!

Fixed with [5e68262](https://github.com/aatikturk/obsws-python/commit/5e68262a8098a32856236519c01a4c56ad39034e)
