### ISSUE TITLE
Trying to find `SetFilenameFormatting()`  method in this library

### ISSUE THREAD

**Issue by devtram** [aatikturk/obsws-python#34]
I am trying to locate `requests.SetFilenameFormatting()` method to set file name of the recording. Can you please help me locate this?

Thank you!

**Comment by aatikturk** [comment]
Hi,

There's no method called  ```requests.SetFilenameFormatting()``` in the current version of the OBSWebSocket. You can check the current ```Requests``` methods [here](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#requests)

There was no method to set the directory/path for recordings when this library was written. But now it seems there is one, described [here](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setrecorddirectory) which is introduced in v5.3.0.

So I'm going to mark this as an enhancement, and keep this open until we implement the newly introduced method.

thanks for pointing this out.

**Comment by devtram** [comment]
Thanks for confirming, I saw a few old libraries of obswebsocket 4.5 has this method. I found it unusual. That's why I asked

**Comment by onyx-and-iris** [comment]
Hey, setting filename formatting was mentioned in #31. Adem is right of course, we need to add SetRecordDirectory.

**Comment by devtram** [comment]
Thanks for referring me to the reference post #31, it worked instantly :)

**Comment by aatikturk** [comment]
Hi,

we've added `set_record_directory()` method   to `ReqClient`. 

To be able to use it, you should have ObsWebsocket v5.3 or higher. (you should enable beta version upgrades under general settings. see the screenshot below) 

![image](https://github.com/aatikturk/obsws-python/assets/34811741/cca67f8c-0358-43a4-bae9-93e5d67872c5)


 Basically it can be used like this:

- create a ReqClient instance
```python3
import obsws_python as obs
cl = obs.ReqClient(host='hostname', port=4455, password='password')
```
- use the method with a string parameter as directory
```python3
cl.set_record_directory("path/to/save")

```
