### ISSUE TITLE
Fullscreen Projector Capability?

### ISSUE THREAD

**Issue by I3lackshirts** [aatikturk/obsws-python#35]
I am looking to set a scene to full screen on one of my monitors but can't seem to find a way. I tried using the open_source_projector or open video mix, only to get an error that the object has no attribute. Here is the reference to the official websocket protocol:

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#openvideomixprojector

Is there a way to do this that I am missing?

**Comment by onyx-and-iris** [comment]
Hi, I assume they weren't added due to the following note:

`Note: This request serves to provide feature parity with 4.x. It is very likely to be changed/deprecated in a future release.`

It's possible they could be added with a deprecation warning. I'll wait to hear Adem's thoughts on this.

**Comment by aatikturk** [comment]
Hi,

As @onyx-and-iris mentioned above, we didn't include [OpenVideoMixProjector](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#openvideomixprojector) and [OpenSourceProjector](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#opensourceprojector) in this library as they'll be deprecated in a future release. But as of v5.3.0 it seems, they're not oficially deprecated.

We may consider implementing these two functions along with SetFilenameFormatting() which we already discussed in #34. 

Please follow #34 for updates.

Thanks

**Comment by I3lackshirts** [comment]
Thanks for the update and appreciate the consideration. Would love to have it included!

**Comment by onyx-and-iris** [comment]
Alright we've added the projector requests. They may change or be removed at any time so be mindful of that if you decide to use them.

Projecting to fullscren is as simple as providing a monitor index. Here is an example:
https://gist.github.com/onyx-and-iris/1204d1f371413c8c62459a5f54017104
