### ISSUE TITLE
Connection times out after few hours and cannot reconnect again

### ISSUE THREAD

**Issue by MattiaMontanari** [aatikturk/obsws-python#45]
Hello,

I have working script that fails after after few hours of successful run.

This is how I start the connection
```
cl = obs.ReqClient(host='localhost', port=4455, password='foo', timeout=30)
```
After a while it stops with a timeout. 
```
websocket._exceptions.WebSocketTimeoutException: Connection timed out
````

Any suggestions other than restarting?

**Comment by onyx-and-iris** [comment]
This sounds like a networking issue and not related to this API. If your connections are closing after several hours I would suggest you catch the raised exception and then handle it in the way you see fit. This doesn't sound like the type of issue we would attempt to handle at the the level of this package.

**Comment by onyx-and-iris** [comment]
Are you not able to simply catch the exception and re-establish a new connection?
