### ISSUE TITLE
failed to start streaming 

### ISSUE THREAD

**Issue by EvenYeah** [aatikturk/obsws-python#47]
# OBS WebSocket setup
import obsws_python as obs

cl = obs.ReqClient(host='localhost', port=4455, timeout=10)
response=cl.send("StartStreaming")#Request StartStreaming returned code 204. With message: Your request type is not valid.

i tried to send a request to make obs start streaming,and i used the request"StartStreaming",but it gave error "Request StartStreaming returned code 204. With message: Your request type is not valid."  
how can i make obs start streaming ?

**Comment by onyx-and-iris** [comment]
Hello, if you want to make calls directly with {ReqClient}.send() then make sure your calls match the api calls exactly. In this case `StartStream`.

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#startstream
